apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nums3-console.fullname" . }}
  labels:
    {{- include "nums3-console.labels" . | nindent 4 }}
data:
  # Configuration pour NumS3-Console
  # Ajoutez vos configurations ici
  # config.json: |
  #   {
  #     "s3": {
  #       "endpoint": "https://s3.amazonaws.com",
  #       "region": "us-east-1"
  #     }
  #   }
