apiVersion: v2
name: outscale-s3-explorer-helm
description: A Helm chart for NumS3-Console deployment on Kubernetes
type: application
version: 999.999.999
appVersion: 999.999.999
keywords:
  - outscale-s3-explorer
  - s3
  - console
  - storage
maintainers:
  - name: Your Name
    email: your.email@example.com
